version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    labels:
      - "mix"
      - "dependencies"
    assignees:
      - "timothyvanderaerden"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    labels:
      - "github-actions"
      - "dependencies"
    assignees:
      - "timothyvanderaerden"
