name: Setup
description: Setup BEAM and compile cache
runs:
  using: composite
  steps:
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp || '26.x'}}
        elixir-version: ${{matrix.elixir || '1.17.x'}}

    - name: Retrieve compile cache
      uses: actions/cache@v4
      id: mix-cache
      with:
        path: |
          deps
          _build
        key: ${{ hashFiles('mix.lock', '.tool-versions') }}
