name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: 27.x
            elixir: 1.17.x
          - otp: 26.x
            elixir: 1.16.x
          - otp: 26.x
            elixir: 1.15.x
          - otp: 26.x
            elixir: 1.14.5

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Setup Elixir and compile cache
        uses: ./.github/actions/setup

      - name: Compile project
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get
          mix deps.compile
          mix compile — warnings-as-errors

      - name: Create PLTs
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt --format github

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Setup Elixir and compile cache
        uses: ./.github/actions/setup

      - name: Check format
        run: mix format --check-formatted

  dialyzer:
    name: Dialyzer
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Setup Elixir and compile cache
        uses: ./.github/actions/setup

      - name: Dialyzer
        run: mix dialyzer --no-check --format github

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: 27.x
            elixir: 1.17.x
          - otp: 26.x
            elixir: 1.16.x
          - otp: 26.x
            elixir: 1.15.x
          - otp: 26.x
            elixir: 1.14.5

    env:
      MIX_ENV: test
    services:
      rabbitmq:
        image: rabbitmq:latest
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Setup Elixir and compile cache
        uses: ./.github/actions/setup

      - name: Retrieve test cache
        uses: actions/cache@v4
        id: mix-cache-test
        with:
          path: _build/test
          key: test-${{ hashFiles('mix.lock') }}

      - name: Run test
        run: mix test
